---
title: "Mapping Assignment"
description: |
    An assignment I completed for an SMPA course titled "Reporting in the Digital Age". I am learning to code using R. 
author:
  - name: Meredith Duffy
    url: https://example.com/meredithduffy
date: 04-20-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


Below I mapped four prominent D.C. locations: the Washington Monument, Tidal Basin, the Pentagon, and the White House.


```{r}

library(readxl)
Coordinates <- read_excel("~/Desktop/Coordinates.xlsx")
View(Coordinates)

leaflet() %>% 
  addTiles() %>% 
  setView(-77.0085764059131, 38.91341734083091,zoom = 12) 

leaflet() %>% 
  addTiles() %>% 
  setView(-77.0085764059131, 38.91341734083091,zoom = 12) 

leaflet() %>% 
  addTiles() %>% 
  setView(-77.0085764059131, 38.91341734083091,zoom = 12) %>% 
  addMarkers(-77.0353, 38.8895) %>% 
  addMarkers(-77.0563,38.8719) %>% 
  addMarkers(-77.0385, 38.8841) %>% 
  addMarkers(-77.0365, 38.8977)


```


Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


